### PR TITLE
Implement Character>>literalPrintOn: for #319

### PR DESCRIPTION
**Pull request by rko281**
Fix for issue #319. Allows EditableListViewDemo to be saved from VC.

### CODE REVIEW

**Comment by rko281** [comment]
Not sure why I've pulled in unrelated commits from my fork, let me know if I need to resubmit.

**Comment by blairmcg** [comment]
John, you've certainly brought through a significant set of extra changes to your EditableListView. The build failed the first time through due to a glitch. I retriggered it, but it then failed due to a missing file. I think it would be preferable to bring those changes through separately since this change is just about making a small fix.

**Comment by rko281** [comment]
Ah... this request was just supposed to pull in the Character fix, with the ELV stuff to follow once I'd reacquainted myself with github. Will revist tomorrow.

**Comment by rko281** [comment]
Resubmitting separately.

**Pull request closed without merging**
