### PR TITLE
Rename a few methods in CommandLine

### PR DESCRIPTION
**Pull request by jgfoster**
Use of the refactoring tool changed the layout of a few methods as well.

### CODE REVIEW

**Comment by jgfoster** [comment]
I'm looking at the failing tests...

**Comment by objectarts** [comment]
Hmm.. it looks like the tests are hanging in AppVeyor. Probably as the result of a walkback in the image.

**Comment by jgfoster** [comment]
I think I have a fix. Testing now...

**Comment by objectarts** [comment]
Great thanks.

**Pull request merged**
